# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Geyser Minecraft Proxy Bridge
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Revolutionize your Minecraft Server with Geyser by allowing Minecraft Bedrock Edition to join your Minecraft Java server.
baseurl: "/GeyserMC-Pages" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: "Etc/UTC"

# Theme settings
logo: https://geysermc.org/img/geyser.png
search_enabled: true
footer_content: "Copyright &copy; 2020 GeyserMC. Distributed by an <a href=\"https://github.com/opencollab-incubator/GeyserMC-Pages/tree/master/LICENSE.txt\">MIT license.</a>"

# GitHub edit link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/opencollab-incubator/GeyserMC-Pages"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

# Top right links
aux_links:
  "GitHub": "https://github.com/GeyserMC/Geyser"
  "Discord": "http://discord.geysermc.org/"

# Remove .html
permalink: /:categories/:year/:month/:day/:title

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
